spring.application.name=Ledger_API

# Might want to change password here as this might be how people intercept into databases and so on

spring.datasource.url=jdbc:postgresql://localhost:5433/Ledger_API
spring.datasource.username=postgres
spring.datasource.password=db

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true