spring.application.name=Ledger_API

# Might want to change password here as this might be how people intercept into databases and so on

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/Ledger_API}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:db}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true